/**
 * redpen: a text inspection tool
 * Copyright (C) 2014 Recruit Technologies Co., Ltd. and contributors
 * (see CONTRIBUTORS.md)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.unigram.docvalidator.validator;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.unigram.docvalidator.store.Document;
import org.unigram.docvalidator.store.FileContent;
import org.unigram.docvalidator.util.CharacterTable;
import org.unigram.docvalidator.util.ResultDistributorFactory;
import org.unigram.docvalidator.util.ValidatorConfiguration;
import org.unigram.docvalidator.util.DVResource;
import org.unigram.docvalidator.util.DocumentValidatorException;
import org.unigram.docvalidator.util.ResultDistributor;
import org.unigram.docvalidator.util.ValidationError;

/**
 * Validate all input files using appended Validators.
 */
public class DocumentValidator {
  /**
   * Constructor.
   *
   * @param resource          configuration settings for DocumentValidator
   * @param resultDistributor output distributor
   * @throws DocumentValidatorException when failed to create the instance
   */
  public DocumentValidator(DVResource resource,
                           ResultDistributor resultDistributor)
      throws DocumentValidatorException {
    this(resource);
    if (resultDistributor == null) {
      throw new DocumentValidatorException("ResultDistributor is null");
    }
    this.distributor = resultDistributor;
  }

  /**
   * Constructor.
   *
   * @param resource configuration settings for DocumentValidator
   * @throws DocumentValidatorException when failed to create the instance
   */
  public DocumentValidator(DVResource resource)
      throws DocumentValidatorException {
    super();
    this.distributor = ResultDistributorFactory.createDistributor("plain",
        System.out);
    this.validators = new ArrayList<Validator>();
    this.conf = resource.getConfiguration();
    this.charTable = resource.getCharacterTable();
    if (!loadValidators()) {
      throw new DocumentValidatorException(
          "Failed to create DocumentValidator");
    }
  }

  /**
   * Load validators written in the configuration file.
   *
   * @return true when succeeded to load all the validators, false otherwise
   */
  @SuppressWarnings("BooleanMethodIsAlwaysInverted")
  public boolean loadValidators() {
    this.validators.clear();
    for (Iterator<ValidatorConfiguration> confIterator =
             this.conf.getChildren(); confIterator.hasNext();) {
      ValidatorConfiguration currentConfiguration = confIterator.next();
      String confName = currentConfiguration.getConfigurationName();
      Validator validator;
      try {
        validator =
            ValidatorFactory.createValidator(confName,
                currentConfiguration, this.charTable);
      } catch (DocumentValidatorException e) {
        LOG.error("Failed to create validator \" "
            + confName + "\" : " + e.getMessage());
        return false;
      }
      this.validators.add(validator);
    }
    return true;
  }

  /**
   * Validate the input document.
   *
   * @param document input document generated by Parser
   * @return list of validation errors
   */
  public List<ValidationError> check(Document document) {
    distributor.flushHeader();
    List<ValidationError> errors = new ArrayList<ValidationError>();
    for (Validator validator : this.validators) {
      Iterator<FileContent> fileIterator = document.getFiles();
      while (fileIterator.hasNext()) {
        try {
          List<ValidationError> currentErrors =
              validator.check(fileIterator.next(), distributor);
          errors.addAll(currentErrors);
        } catch (Throwable e) {
          LOG.error("Error occurs in validation: " + e.getMessage());
          LOG.error("Validator class: " + validator.getClass());
        }
      }
    }
    distributor.flushFooter();
    return errors;
  }

  /**
   * Constructor only for testing.
   */
  protected DocumentValidator() {
    this.distributor = ResultDistributorFactory.createDistributor("plain",
        System.out);
    this.validators = new ArrayList<Validator>();
    this.conf = null;
    this.charTable = null;
  }

  /**
   * Append a specified validator.
   *
   * @param validator Validator used in testing
   */
  protected void appendValidator(Validator validator) {
    this.validators.add(validator);
  }

  private final List<Validator> validators;

  private final ValidatorConfiguration conf;

  private final CharacterTable charTable;

  private ResultDistributor distributor;

  private static final Logger LOG =
      LoggerFactory.getLogger(DocumentValidator.class);
}
